# Minimal Makefile for Sphinx docs
SPHINXBUILD := sphinx-build
SOURCEDIR := source
BUILDDIR  := _build

.PHONY: html
html:
	$(SPHINXBUILD) -b html $(SOURCEDIR) $(BUILDDIR)/html
	@echo "Build finished. The HTML pages are in $(BUILDDIR)/html"