/*
 .-..-.      .---.       _                  
 : :; :      : .; :     :_;                 
 :    :.-..-.:  _.'.--. .-. .--. ,-.,-.,-.  
 : :: :: :; :: :   : ..': :`._-.': ,. ,. : 
 :_;:_;`._. ;:_;   :_;  :_;`.__.':_;:_;:_;
        .-. :                               
        `._.'            generated IPC API 

AUTO-GENERATED BY generate-ipc.mjs — DO NOT EDIT MANUALLY!
SOURCE: Services/Core/IpcService.cs (@type + @ipc annotations)
*/

// eslint-disable-next-line @typescript-eslint/no-require-imports
const { ipcRenderer } = (window as any).require('electron');

// #region Core IPC helpers

export function send(channel: string, data?: unknown): void {
  ipcRenderer.send(channel, data != null ? JSON.stringify(data) : undefined);
}

export function on(channel: string, callback: (data: unknown) => void): () => void {
  const listener = (_event: unknown, ...args: unknown[]) => {
    const raw = args.length === 1 ? args[0] : args;
    // Backend sends JSON.Serialize(data), so we need to parse it
    let parsed = raw;
    if (typeof raw === 'string') {
      try { parsed = JSON.parse(raw); } catch { /* keep raw */ }
    }
    callback(parsed);
  };
  ipcRenderer.on(channel, listener);
  return () => { ipcRenderer.removeListener(channel, listener); };
}

export function invoke<T = unknown>(channel: string, data?: unknown, timeout = 10000): Promise<T> {
  return new Promise((resolve, reject) => {
    const replyChannel = `${channel}:reply`;
    const timer = setTimeout(() => {
      cleanup();
      reject(new Error(`IPC timeout on ${channel}`));
    }, timeout);

    const cleanup = on(replyChannel, (response) => {
      clearTimeout(timer);
      cleanup();
      try {
        const parsed = typeof response === 'string' ? JSON.parse(response) : response;
        resolve(parsed as T);
      } catch {
        resolve(response as T);
      }
    });

    send(channel, data);
  });
}

// #endregion

// #region Types (from @type annotations)

export interface ProgressUpdate {
  state: string;
  progress: number;
  messageKey: string;
  args?: unknown[];
  downloadedBytes: number;
  totalBytes: number;
}

export interface GameState {
  state: 'starting' | 'started' | 'running' | 'stopped';
  exitCode: number;
}

export interface GameError {
  type: string;
  message: string;
  technical?: string;
}

export interface NewsItem {
  title: string;
  excerpt?: string;
  url?: string;
  date?: string;
  publishedAt?: string;
  author?: string;
  imageUrl?: string;
  source?: string;
}

export interface Profile {
  id: string;
  name: string;
  uuid?: string;
  isOfficial?: boolean;
  avatar?: string;
  folderName?: string;
}

export interface HytaleAuthStatus {
  loggedIn: boolean;
  username?: string;
  uuid?: string;
  error?: string;
  errorType?: string;
}

export interface ProfileSnapshot {
  nick: string;
  uuid: string;
  avatarPath?: string;
}

export interface SettingsSnapshot {
  language: string;
  musicEnabled: boolean;
  launcherBranch: string;
  closeAfterLaunch: boolean;
  showDiscordAnnouncements: boolean;
  disableNews: boolean;
  backgroundMode: string;
  availableBackgrounds: string[];
  accentColor: string;
  hasCompletedOnboarding: boolean;
  onlineMode: boolean;
  authDomain: string;
  dataDirectory: string;
  instanceDirectory: string;
  gpuPreference?: string;
  launchOnStartup?: boolean;
  minimizeToTray?: boolean;
  animations?: boolean;
  transparency?: boolean;
  resolution?: string;
  ramMb?: number;
  sound?: boolean;
  closeOnLaunch?: boolean;
  developerMode?: boolean;
  verboseLogging?: boolean;
  preRelease?: boolean;
  [key: string]: unknown;
}

export interface ModScreenshot {
  id: number;
  title: string;
  thumbnailUrl: string;
  url: string;
}

export interface ModInfo {
  id: string;
  name: string;
  slug: string;
  summary: string;
  author: string;
  downloadCount: number;
  iconUrl: string;
  thumbnailUrl: string;
  categories: string[];
  dateUpdated: string;
  latestFileId: string;
  screenshots: ModScreenshot[];
}

export interface ModSearchResult {
  mods: ModInfo[];
  totalCount: number;
}

export interface ModFileInfo {
  id: string;
  modId: string;
  fileName: string;
  displayName: string;
  downloadUrl: string;
  fileLength: number;
  fileDate: string;
  releaseType: number;
  gameVersions: string[];
  downloadCount: number;
}

export interface ModFilesResult {
  files: ModFileInfo[];
  totalCount: number;
}

export interface ModCategory {
  id: number;
  name: string;
  slug: string;
}

export interface InstalledMod {
  id: string;
  name: string;
  slug?: string;
  version?: string;
  fileId?: string;
  fileName?: string;
  enabled: boolean;
  author?: string;
  description?: string;
  iconUrl?: string;
  curseForgeId?: string;
  fileDate?: string;
  releaseType?: number;
  latestFileId?: string;
  latestVersion?: string;
  screenshots?: ModScreenshot[];
}

export interface SaveInfo {
  name: string;
  previewPath?: string;
  lastModified?: string;
  sizeBytes?: number;
}

export interface AppConfig {
  language: string;
  dataDirectory: string;
  [key: string]: unknown;
}

export interface InstanceValidationDetails {
  hasExecutable: boolean;
  hasAssets: boolean;
  hasLibraries: boolean;
  hasConfig: boolean;
  missingComponents: string[];
  errorMessage?: string;
}

export interface InstalledInstance {
  id: string;
  branch: string;
  version: number;
  path: string;
  hasUserData: boolean;
  userDataSize: number;
  totalSize: number;
  isValid: boolean;
  validationStatus?: 'Valid' | 'NotInstalled' | 'Corrupted' | 'Unknown';
  validationDetails?: InstanceValidationDetails;
  customName?: string;
}

export interface InstanceInfo {
  id: string;
  name: string;
  branch: string;
  version: number;
  isInstalled: boolean;
}

export interface LanguageInfo {
  code: string;
  name: string;
}

export interface GpuAdapterInfo {
  name: string;
  vendor: string;
  type: string;
}

export interface VersionInfo {
  version: number;
  source: 'Official' | 'Mirror';
  isLatest: boolean;
}

export interface VersionListResponse {
  versions: VersionInfo[];
  hasOfficialAccount: boolean;
  officialSourceAvailable: boolean;
}

// #endregion

// #region Typed IPC API (from @ipc annotations)

const _config = {
  get: () => invoke<AppConfig>('hyprism:config:get'),
  save: (data?: unknown) => invoke<{ success: boolean }>('hyprism:config:save', data),
};

const _game = {
  launch: (data?: unknown) => send('hyprism:game:launch', data),
  cancel: (data?: unknown) => send('hyprism:game:cancel', data),
  stop: (data?: unknown) => invoke<boolean>('hyprism:game:stop', data),
  instances: () => invoke<InstalledInstance[]>('hyprism:game:instances'),
  isRunning: (data?: unknown) => invoke<boolean>('hyprism:game:isRunning', data),
  versions: (data?: unknown) => invoke<number[]>('hyprism:game:versions', data),
  onProgress: (cb: (data: ProgressUpdate) => void) => on('hyprism:game:progress', cb as (d: unknown) => void),
  onState: (cb: (data: GameState) => void) => on('hyprism:game:state', cb as (d: unknown) => void),
  onError: (cb: (data: GameError) => void) => on('hyprism:game:error', cb as (d: unknown) => void),
  versionsWithSources: (data?: unknown) => invoke<VersionListResponse>('hyprism:game:versionsWithSources', data),
};

const _instance = {
  create: (data?: unknown) => invoke<InstanceInfo | null>('hyprism:instance:create', data),
  delete: (data?: unknown) => invoke<boolean>('hyprism:instance:delete', data),
  openFolder: (data?: unknown) => send('hyprism:instance:openFolder', data),
  openModsFolder: (data?: unknown) => send('hyprism:instance:openModsFolder', data),
  export: (data?: unknown) => invoke<string>('hyprism:instance:export', data),
  import: (data?: unknown) => invoke<boolean>('hyprism:instance:import', data),
  saves: (data?: unknown) => invoke<SaveInfo[]>('hyprism:instance:saves', data),
  openSaveFolder: (data?: unknown) => send('hyprism:instance:openSaveFolder', data),
  getIcon: (data?: unknown) => invoke<string | null>('hyprism:instance:getIcon', data),
  select: (data?: unknown) => invoke<boolean>('hyprism:instance:select', data),
  getSelected: (data?: unknown) => invoke<InstanceInfo | null>('hyprism:instance:getSelected', data),
  list: () => invoke<InstanceInfo[]>('hyprism:instance:list'),
};

const _news = {
  get: () => invoke<NewsItem[]>('hyprism:news:get'),
};

const _profile = {
  get: () => invoke<ProfileSnapshot>('hyprism:profile:get'),
  list: () => invoke<Profile[]>('hyprism:profile:list'),
  switch: (data?: unknown) => invoke<{ success: boolean }>('hyprism:profile:switch', data),
  setNick: (data?: unknown) => invoke<{ success: boolean }>('hyprism:profile:setNick', data),
  setUuid: (data?: unknown) => invoke<{ success: boolean }>('hyprism:profile:setUuid', data),
  create: (data?: unknown) => invoke<Profile>('hyprism:profile:create', data),
  delete: (data?: unknown) => invoke<{ success: boolean }>('hyprism:profile:delete', data),
  activeIndex: (data?: unknown) => invoke<number>('hyprism:profile:activeIndex', data),
  save: (data?: unknown) => invoke<{ success: boolean }>('hyprism:profile:save', data),
  duplicate: (data?: unknown) => invoke<Profile>('hyprism:profile:duplicate', data),
  openFolder: (data?: unknown) => send('hyprism:profile:openFolder', data),
  avatarForUuid: (data?: unknown) => invoke<string>('hyprism:profile:avatarForUuid', data),
};

const _auth = {
  status: (data?: unknown) => invoke<HytaleAuthStatus>('hyprism:auth:status', data),
  login: (data?: unknown) => invoke<HytaleAuthStatus>('hyprism:auth:login', data),
  logout: (data?: unknown) => invoke<{ success: boolean }>('hyprism:auth:logout', data),
};

const _settings = {
  get: () => invoke<SettingsSnapshot>('hyprism:settings:get'),
  update: (data?: unknown) => invoke<{ success: boolean }>('hyprism:settings:update', data),
  launcherPath: (data?: unknown) => invoke<string>('hyprism:settings:launcherPath', data),
  defaultInstanceDir: (data?: unknown) => invoke<string>('hyprism:settings:defaultInstanceDir', data),
  setInstanceDir: (data?: unknown) => invoke<{ success: boolean, path: string, noop?: boolean, reason?: string, error?: string }>('hyprism:settings:setInstanceDir', data, 300000),
};

const _i18n = {
  get: () => invoke<Record<string, string>>('hyprism:i18n:get'),
  current: () => invoke<string>('hyprism:i18n:current'),
  set: (data?: unknown) => invoke<{ success: boolean, language: string }>('hyprism:i18n:set', data),
  languages: () => invoke<LanguageInfo[]>('hyprism:i18n:languages'),
};

const _window = {
  minimize: (data?: unknown) => send('hyprism:window:minimize', data),
  maximize: (data?: unknown) => send('hyprism:window:maximize', data),
  close: (data?: unknown) => send('hyprism:window:close', data),
  restart: (data?: unknown) => send('hyprism:window:restart', data),
};

const _browser = {
  open: (data: string) => send('hyprism:browser:open', data),
};

const _mods = {
  list: () => invoke<InstalledMod[]>('hyprism:mods:list'),
  search: (data?: unknown) => invoke<ModSearchResult>('hyprism:mods:search', data, 15000),
  installed: (data?: unknown) => invoke<InstalledMod[]>('hyprism:mods:installed', data),
  uninstall: (data?: unknown) => invoke<boolean>('hyprism:mods:uninstall', data),
  checkUpdates: (data?: unknown) => invoke<InstalledMod[]>('hyprism:mods:checkUpdates', data, 30000),
  install: (data?: unknown) => invoke<boolean>('hyprism:mods:install', data, 30000),
  files: (data?: unknown) => invoke<ModFilesResult>('hyprism:mods:files', data),
  categories: (data?: unknown) => invoke<ModCategory[]>('hyprism:mods:categories', data),
  installLocal: (data?: unknown) => invoke<boolean>('hyprism:mods:installLocal', data),
  installBase64: (data?: unknown) => invoke<boolean>('hyprism:mods:installBase64', data),
  openFolder: (data?: unknown) => send('hyprism:mods:openFolder', data),
  toggle: (data?: unknown) => invoke<boolean>('hyprism:mods:toggle', data),
  exportToFolder: (data?: unknown) => invoke<string>('hyprism:mods:exportToFolder', data),
  importList: (data?: unknown) => invoke<number>('hyprism:mods:importList', data),
};

const _system = {
  gpuAdapters: () => invoke<GpuAdapterInfo[]>('hyprism:system:gpuAdapters'),
};

const _console = {
  log: (msg: string) => send('hyprism:console:log', msg),
  warn: (msg: string) => send('hyprism:console:warn', msg),
  error: (msg: string) => send('hyprism:console:error', msg),
};

const _logs = {
  get: () => invoke<string[]>('hyprism:logs:get'),
};

const _file = {
  browseFolder: (data?: unknown) => invoke<string | null>('hyprism:file:browseFolder', data),
  browseModFiles: (data?: unknown) => invoke<string[]>('hyprism:file:browseModFiles', data),
};

// #endregion

// #region Unified export

export const ipc = {
  config: _config,
  game: _game,
  instance: _instance,
  news: _news,
  profile: _profile,
  auth: _auth,
  settings: _settings,
  i18n: _i18n,
  windowCtl: _window,
  browser: _browser,
  mods: _mods,
  system: _system,
  consoleCtl: _console,
  logs: _logs,
  file: _file,
};

// #endregion
